
# These are the defaults for a user's settings that are
# automatically loaded, and then overridden by the project's settings

flex-path:

flake-files:
  - Flakefile
  - flakefile
  - flake
  - flake.project
